### ISSUE TITLE
Will you make a website by using github pages?

### ISSUE THREAD

**Issue by FluuFlaaT** [howdareyou630/xiaozhan630#6]

**Comment by FluuFlaaT** [comment]
I think it is a better way to let more people know what we are working for. As GitHub has been blocked in China Mainland, Github Pages can be a good way to show them.

**Comment by howdareyou630** [comment]
Yep, But the data is not ample, Maybe a little bit later.

**Comment by Iyme** [comment]
Long way to go, it's hard to study witch style the usr prefer, and find the UI designers
